apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  baseImage: couchbase/server
  version: enterprise-6.0.1
  authSecret: cb-example-auth
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 30
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    - name: couchmart
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: low
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
    - name: metadata
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: low
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
    - name: fulfillment
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: low
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  servers:
    - size: 3
      name: data_service
      services:
        - data
    - size: 1
      name: index_query_service
      services:
        - index
        - query
    - size: 1
      name: search_service
      services:
       - search
    - size: 1
      name: analytics_service
      services:
        - analytics
    - size: 1
      name: eventing_service
      services:
        - eventing
        
