kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: translatorapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: translatorapp
        version: v1
    spec:
      containers:
      - name: translatorapp
        image: docker-registry.default.svc:5000/translatorapp/translatorapp:latest
        ports:
        - containerPort: 3000
      restartPolicy: Always
